language: python
python: "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"
sudo: required
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base

# command to run tests
